# Generated by Django 3.2 on 2024-11-07 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_]+$', 'Символы латинского алфавита, цифры и знак подчёркивания')], verbose_name='Слаг'),
        ),
    ]
